# Generated by Django 4.0 on 2022-01-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_core', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('staff_perms', 'Staff permissions'))},
        ),
    ]
